export const Products2 = [
    {
        id: 16,
        image: '/images-for-bazargam/butter2.jpg',
        name: ' کره حیوانی 100 گرمی تنظیم بازار',
        weight: 2444,
        price: 1222,
        discount: 41,
        runOut: true,
    },
    {
        id: 17,
        image: '/images-for-bazargam/mast.jpg',
        name: 'ماست پرچرب می ماس تنظیم بازار',
        weight: 1299,
        price: 3222,
        discount: 0,
        runOut: false,
    },
    {
        id: 18,
        image: '/images-for-bazargam/makaroni.jpg',
        name: ' ماکارونی1/2رشته ای تنظیم بازار',
        weight: 7666,
        price: 4333,
        discount: 0,
        runOut: false,
    },
    {
        id: 19,
        image: '/images-for-bazargam/khoshk.jpg',
        name: 'میوه خشک مخلوط',
        weight: 4333,
        price: 5333,
        discount: 0,
        runOut: false,
    },
    {
        id: 20,
        image: '/images-for-bazargam/carrot.jpg',
        name: 'هویج',
        weight: 2111,
        price: 2111,
        discount: 0,
        runOut: false,
    },
    {
        id: 21,
        image: '/images-for-bazargam/nana.jpg',
        name: 'نعنا',
        weight: 6555,
        price: 4333,
        discount: 0,
        runOut: false,
    },
    {
        id: 22,
        image: '/images-for-bazargam/khame.jpg',
        name: 'خامه',
        weight: 4333,
        price: 3222,
        discount: 0,
        runOut: false,
    },
    {
        id: 23,
        image: '/images-for-bazargam/gharch.jpg',
        name: 'قارج',
        weight: 5444,
        price: 2311,
        discount: 21,
        runOut: false,
    },
]