export const Products1 = [
    {
        id: 1,
        image: '/images-for-bazargam/peste.png',
        name: " پسته بو داده نمکین ممتاز گلستان 300گرمی",
        weight: 1200,
        price: 2300,
        discount: 41,
        runOut: true,
    },
    {
        id: 2,
        image: '/images-for-bazargam/potato.jpg',
        name: 'سیب زمینی',
        weight: 1244,
        price: 1000,
        discount: 0,
        runOut: false,
    },
    {
        id: 3,
        image: '/images-for-bazargam/hen.jpg',
        name: 'مرغ تنظیم بازار',
        weight: 3222,
        price: 3800,
        discount: 0,
        runOut: false,
    },
    {
        id: 4,
        image: '/images-for-bazargam/egg.jpg',
        name: 'تخم مرغ تنظیم بازار',
        weight: 4333,
        price: 5433,
        discount: 0,
        runOut: false,
    },
    {
        id: 5,
        image: '/images-for-bazargam/indian.jpg',
        name: 'برنج هندی تنظیم بازار',
        weight: 3222,
        price: 7600,
        discount: 0,
        runOut: false,
    },
    {
        id: 6,
        image: '/images-for-bazargam/pakistanian.jpg',
        name: 'برنج پاکستانی تنظیم بازار',
        weight: 3222,
        price: 1278,
        discount: 0,
        runOut: false,
    },
    {
        id: 7,
        image: '/images-for-bazargam/shirudi.jpg',
        name: 'برنج شیرودی تنظیم بازار',
        weight: 2111,
        price: 4321,
        discount: 0,
        runOut: false,
    },
    {
        id: 8,
        image: '/images-for-bazargam/tailandi.jpg',
        name: 'برنج تایلندی تنظیم بازار',
        weight: 1333,
        price: 6753,
        discount: 24,
        runOut: false,
    },
    {
        id: 9,
        image: '/images-for-bazargam/roghan1.jpg',
        name: 'روغن مایع آفتابگردان آفتاب1350گرمی تنظیم بازار',
        weight: 4333,
        price: 4865,
        discount: 0,
        runOut: true,
    },
    {
        id: 10,
        image: '/images-for-bazargam/roghan2.jpg',
        name: 'روغن مایع سرخ کردنی آفتاب1350گرمی تنظیم بازار',
        weight: 2111,
        price: 4578,
        discount: 0,
        runOut: false,
    },
    {
        id: 11,
        image: '/images-for-bazargam/roghan3.jpg',
        name: 'روغن مایع سرخ کردنی ویژه آفتاب1350گرمی تنظیم بازار',
        weight: 6555,
        price: 3243,
        discount: 0,
        runOut: false,
    },
    {
        id: 12,
        image: '/images-for-bazargam/butter.jpg',
        name: 'کره حیوانی 50 گرمی تنظیم بازار',
        weight: 4333,
        price: 8753,
        discount: 0,
        runOut: true,
    },
    {
        id: 13,
        image: '/images-for-bazargam/meat.jpg',
        name: 'گردن گوساله منجمد بسته بندی تنظیم بازار',
        weight: 4333,
        price: 3245,
        discount: 11,
        runOut: false,
    },
    {
        id: 14,
        image: '/images-for-bazargam/orange.jpg',
        name: 'پرتقال تامسون شمال سبدی تنظیم بازار',
        weight: 3222,
        price: 6421,
        discount: 0,
        runOut: false,
    },
    {
        id: 15,
        image: '/images-for-bazargam/apple.png',
        name: 'سیب زرد سبدی تنظیم بازار',
        weight: 4111,
        price: 3421,
        discount: 0,
        runOut: true,
    },

]